### ISSUE TITLE
`ron --help` raises undefined method `grep' error

### ISSUE THREAD

**Issue by sunaku** [rtomayko/ronn#10]
```
# gem list ron
*** LOCAL GEMS ***
ron (0.3)

# ruby -v
ruby 1.9.1p376 (2009-12-07 revision 26041) [i686-linux]

# ron --help
/usr/lib/ruby/gems/1.9.1/gems/ron-0.3/bin/ron:47:in `usage': undefined method `grep' for #<String:0x8fc8648> (NoMethodError)
        from /usr/lib/ruby/gems/1.9.1/gems/ron-0.3/bin/ron:71:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/1.9.1/optparse.rb:1271:in `call'
        from /usr/lib/ruby/1.9.1/optparse.rb:1271:in `block in parse_in_order'
        from /usr/lib/ruby/1.9.1/optparse.rb:1258:in `catch'
        from /usr/lib/ruby/1.9.1/optparse.rb:1258:in `parse_in_order'
        from /usr/lib/ruby/1.9.1/optparse.rb:1252:in `order!'
        from /usr/lib/ruby/1.9.1/optparse.rb:1343:in `permute!'
        from /usr/lib/ruby/1.9.1/optparse.rb:1364:in `parse!'
        from /usr/lib/ruby/gems/1.9.1/gems/ron-0.3/bin/ron:72:in `block in <top (required)>'
        from /usr/lib/ruby/1.9.1/optparse.rb:1738:in `options'
        from /usr/lib/ruby/gems/1.9.1/gems/ron-0.3/bin/ron:54:in `<top (required)>'
        from /usr/bin/ron:19:in `load'
        from /usr/bin/ron:19:in `<main>'
```

**Comment by rtomayko** [comment]
Merged patch from hallison. Thanks everyone.
