### ISSUE TITLE
Get an error when trying to add custom css

### ISSUE THREAD

**Issue by trans** [rtomayko/ronn#39]
I do:

```
$ RONN_STYLE='./.config/ronn'; ronn -br5 --organization=PROUTILS --style='man,toc,center' --manual='Roll Manual' man/*.ronn
```

And get:

```
roff: man/roll-copy.1                            
html: man/roll-copy.1.html                       +man,toc,center
/usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:100:in `basename': can't convert nil into String (TypeError)
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:100:in `stylesheets'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:99:in `map'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:99:in `stylesheets'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:113:in `stylesheet_tags'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/context.rb:97:in `__send__'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/context.rb:97:in `fetch'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/context.rb:85:in `each'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/context.rb:85:in `fetch'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/context.rb:67:in `[]'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/template.rb:40:in `render'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache/template.rb:44:in `render'
from /usr/lib/ruby/gems/1.8/gems/mustache-0.11.2/lib/mustache.rb:347:in `render'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/template.rb:14:in `render'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/document.rb:244:in `to_html'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/document.rb:221:in `send'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/lib/ronn/document.rb:221:in `convert'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/bin/ronn:191
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/bin/ronn:181:in `each'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/bin/ronn:181
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/bin/ronn:167:in `each'
from /usr/lib/ruby/gems/1.8/gems/ronn-0.7.3/bin/ronn:167
from /usr/local/lib/site_ruby/1.8/roll/library.rb:726:in `load_without_rolls'
from /usr/local/lib/site_ruby/1.8/roll/library.rb:726:in `load'
from /usr/local/lib/site_ruby/1.8/roll/kernel.rb:38:in `load'
from /usr/bin/ronn:19
```

**Comment by badboy** [comment]
tried it without the semicolon (;) after RONN_STYLE='./.config/ronn' ?

**Comment by trans** [comment]
Ahhhh, it couldn't find 'center.css'.  ok. error message could be a little moire helpful. but i got it now. thank you much, sir.
