### ISSUE TITLE
`sniff': uninitialized constant Ronn::Document::Markdown (NameError)

### ISSUE THREAD

**Issue by skull-squadron** [rtomayko/ronn#87]
``` shell
$ ronn /Users/bmf/.gem/ruby/2.2.0/gems/bundler-1.7.10/man/bundle-config.ronn
/Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/lib/ronn/document.rb:191:in `sniff': uninitialized constant Markdown (NameError)
    from /Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/lib/ronn/document.rb:76:in `initialize'
    from /Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/bin/ronn:166:in `new'
    from /Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/bin/ronn:166:in `block in <top (required)>'
    from /Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/bin/ronn:166:in `map'
    from /Users/bmf/.gem/ruby/2.2.0/gems/ronn-0.7.3/bin/ronn:166:in `<top (required)>'
    from /Users/bmf/.gem/ruby/2.2.0/bin/ronn:23:in `load'
    from /Users/bmf/.gem/ruby/2.2.0/bin/ronn:23:in `<main>'
$
```

This is a cross-domain issue, apparently a conflict in the order between how Ruby _native extensions_ and Ruby _files_ are loaded, specifically in rdiscount.

```
...
/Users/bmf/.gem/ruby/2.2.0/gems/rdiscount-1.6.8/lib/rdiscount.bundle
/Users/bmf/.gem/ruby/2.2.0/gems/rdiscount-1.6.8/lib/rdiscount.rb
...
```

  There's a [PR in RubyGems](https://github.com/rubygems/rubygems/pull/1137) to swap the order, and so fixing this issue, however it seems it may take a little more retooling to not break things and to fix it for the future.

MRI 2.2.0
RubyGems 2.4.5
bundler 1.7.10
ronn 0.7.3
rdiscount 1.6.8
OSX

**Comment by skull-squadron** [comment]
Submitted for thoroughness.  This project appears to be unmaintained, and so closing.
